<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Michael Foley" />

<meta name="date" content="2021-12-26" />

<title>Ethnicity and Self-Identity</title>

<script src="site_libs/header-attrs-2.11/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/flatly.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>


<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: visible;
  }
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; } /* Alert */
code span.an { color: #008000; } /* Annotation */
code span.at { } /* Attribute */
code span.bu { } /* BuiltIn */
code span.cf { color: #0000ff; } /* ControlFlow */
code span.ch { color: #008080; } /* Char */
code span.cn { } /* Constant */
code span.co { color: #008000; } /* Comment */
code span.cv { color: #008000; } /* CommentVar */
code span.do { color: #008000; } /* Documentation */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.im { } /* Import */
code span.in { color: #008000; } /* Information */
code span.kw { color: #0000ff; } /* Keyword */
code span.op { } /* Operator */
code span.ot { color: #ff4000; } /* Other */
code span.pp { color: #ff4000; } /* Preprocessor */
code span.sc { color: #008080; } /* SpecialChar */
code span.ss { color: #008080; } /* SpecialString */
code span.st { color: #008080; } /* String */
code span.va { } /* Variable */
code span.vs { color: #008080; } /* VerbatimString */
code span.wa { color: #008000; font-weight: bold; } /* Warning */

.sourceCode .row {
  width: 100%;
}
.sourceCode {
  overflow-x: auto;
}
.code-folding-btn {
  margin-right: -30px;
}
</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    for (var j = 0; j < rules.length; j++) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") continue;
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') continue;
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>




<link rel="stylesheet" href="style.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>



<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Ethnicity and Self-Identity</h1>
<h3 class="subtitle">Exploration of 2020 Pew Research Center Survey</h3>
<h4 class="author">Michael Foley</h4>
<h4 class="date">2021-12-26</h4>

</div>


<p>Ipsos Public Affairs (Ipsos) conducted a survey on behalf of Pew Research from Jan 3-13, 2020 related to knowledge and attitudes about the 2020 census. The target population was non-institutionalized adults age 18 and older residing in the United States. The survey was conducted in part to explore the impact of a change in questions related to race and ethnicity. This project further explores racial/ethnic identity, estimating its relationship with other social and demographic factors: age, gender, education, and state of residence.</p>
<div id="load-data-set" class="section level1">
<h1>Load Data Set</h1>
<p>The <a href="https://www.pewresearch.org/social-trends/dataset/2020-census-survey-1/">2020 Census survey #1</a> data set is available for download at the PEW Research web site.<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a></p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r fold-show"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pew_dat_0 <span class="ot">&lt;-</span> foreign<span class="sc">::</span><span class="fu">read.spss</span>(</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">&quot;../data/Jan20 Census_cleaned dataset.sav&quot;</span>, </span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">to.data.frame =</span> <span class="cn">TRUE</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(pew_dat_0)</span></code></pre></div>
<pre><code>## [1] 3535  156</code></pre>
<p>The data set consists of 156 variables collected from 3,535 participants. Only a fraction of the columns are of interest for this analysis.<a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a></p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>pew_dat_1 <span class="ot">&lt;-</span> pew_dat_0 <span class="sc">%&gt;%</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">CENRACE2020 =</span> <span class="fu">case_when</span>(</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>      CENRACE2020_1  <span class="sc">==</span> <span class="st">&quot;Yes&quot;</span> <span class="sc">~</span> <span class="st">&quot;White&quot;</span>,</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>      CENRACE2020_2  <span class="sc">==</span> <span class="st">&quot;Yes&quot;</span> <span class="sc">~</span> <span class="st">&quot;Black&quot;</span>, <span class="co"># Black or African American</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>      CENRACE2020_3  <span class="sc">==</span> <span class="st">&quot;Yes&quot;</span> <span class="sc">~</span> <span class="st">&quot;Other&quot;</span>, <span class="co"># American Indian or Alaska Native</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>      CENRACE2020_4  <span class="sc">==</span> <span class="st">&quot;Yes&quot;</span> <span class="sc">~</span> <span class="st">&quot;Asian&quot;</span>, <span class="co"># Chinese</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>      CENRACE2020_5  <span class="sc">==</span> <span class="st">&quot;Yes&quot;</span> <span class="sc">~</span> <span class="st">&quot;Asian&quot;</span>, <span class="co"># Filipino</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>      CENRACE2020_6  <span class="sc">==</span> <span class="st">&quot;Yes&quot;</span> <span class="sc">~</span> <span class="st">&quot;Asian&quot;</span>, <span class="co"># Asian Indian</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>      CENRACE2020_7  <span class="sc">==</span> <span class="st">&quot;Yes&quot;</span> <span class="sc">~</span> <span class="st">&quot;Asian&quot;</span>, <span class="co"># Vietnamese</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>      CENRACE2020_8  <span class="sc">==</span> <span class="st">&quot;Yes&quot;</span> <span class="sc">~</span> <span class="st">&quot;Asian&quot;</span>, <span class="co"># Korean</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>      CENRACE2020_9  <span class="sc">==</span> <span class="st">&quot;Yes&quot;</span> <span class="sc">~</span> <span class="st">&quot;Asian&quot;</span>, <span class="co"># Japanese</span></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>      CENRACE2020_10 <span class="sc">==</span> <span class="st">&quot;Yes&quot;</span> <span class="sc">~</span> <span class="st">&quot;Asian&quot;</span>, <span class="co"># Other Asian</span></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>      CENRACE2020_11 <span class="sc">==</span> <span class="st">&quot;Yes&quot;</span> <span class="sc">~</span> <span class="st">&quot;Pacific Islander&quot;</span>, <span class="co"># Native Hawaiian</span></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>      CENRACE2020_12 <span class="sc">==</span> <span class="st">&quot;Yes&quot;</span> <span class="sc">~</span> <span class="st">&quot;Pacific Islander&quot;</span>, <span class="co"># Samoan</span></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>      CENRACE2020_13 <span class="sc">==</span> <span class="st">&quot;Yes&quot;</span> <span class="sc">~</span> <span class="st">&quot;Pacific Islander&quot;</span>, <span class="co"># Chamorro</span></span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>      CENRACE2020_14 <span class="sc">==</span> <span class="st">&quot;Yes&quot;</span> <span class="sc">~</span> <span class="st">&quot;Pacific Islander&quot;</span>, <span class="co"># Other Pacific Islander</span></span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>      CENRACE2020_15 <span class="sc">==</span> <span class="st">&quot;Yes&quot;</span> <span class="sc">~</span> <span class="st">&quot;Other&quot;</span>, <span class="co"># Some other race</span></span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">&quot;Other&quot;</span></span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">simple_eth =</span> <span class="fu">factor</span>(</span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>      <span class="fu">case_when</span>(</span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a>        racnum <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> CENHISPAN2020_1 <span class="sc">==</span> <span class="st">&quot;Yes&quot;</span> <span class="sc">&amp;</span> CENRACE2020 <span class="sc">==</span> <span class="st">&quot;White&quot;</span> <span class="sc">~</span> <span class="st">&quot;White&quot;</span>,</span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a>        racnum <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> CENHISPAN2020_1 <span class="sc">==</span> <span class="st">&quot;Yes&quot;</span> <span class="sc">&amp;</span> CENRACE2020 <span class="sc">==</span> <span class="st">&quot;Black&quot;</span> <span class="sc">~</span> <span class="st">&quot;Black&quot;</span>,</span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a>        racnum <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> CENHISPAN2020_1 <span class="sc">==</span> <span class="st">&quot;No&quot;</span> <span class="sc">~</span> <span class="st">&quot;Hispanic&quot;</span>,</span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a>        <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">&quot;Other&quot;</span></span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a>      ),</span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a>      <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">&quot;White&quot;</span>, <span class="st">&quot;Black&quot;</span>, <span class="st">&quot;Hispanic&quot;</span>, <span class="st">&quot;Other&quot;</span>)</span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb3-30"><a href="#cb3-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">CENIDENTITYa =</span> <span class="fu">factor</span>(</span>
<span id="cb3-31"><a href="#cb3-31" aria-hidden="true" tabindex="-1"></a>      CENIDENTITYa, </span>
<span id="cb3-32"><a href="#cb3-32" aria-hidden="true" tabindex="-1"></a>      <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">&quot;My origin is not central to my identity&quot;</span>, </span>
<span id="cb3-33"><a href="#cb3-33" aria-hidden="true" tabindex="-1"></a>                 <span class="st">&quot;My origin is central to my identity&quot;</span>, </span>
<span id="cb3-34"><a href="#cb3-34" aria-hidden="true" tabindex="-1"></a>                 <span class="st">&quot;Refused&quot;</span>),</span>
<span id="cb3-35"><a href="#cb3-35" aria-hidden="true" tabindex="-1"></a>      <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Not central&quot;</span>, <span class="st">&quot;Central&quot;</span>, <span class="st">&quot;Refused&quot;</span>)</span>
<span id="cb3-36"><a href="#cb3-36" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb3-37"><a href="#cb3-37" aria-hidden="true" tabindex="-1"></a>    <span class="at">CENIDENTITYb =</span> <span class="fu">factor</span>(</span>
<span id="cb3-38"><a href="#cb3-38" aria-hidden="true" tabindex="-1"></a>      CENIDENTITYb, </span>
<span id="cb3-39"><a href="#cb3-39" aria-hidden="true" tabindex="-1"></a>      <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">&quot;I am not too familiar with my origins&quot;</span>, </span>
<span id="cb3-40"><a href="#cb3-40" aria-hidden="true" tabindex="-1"></a>                 <span class="st">&quot;I am very familiar with my origins&quot;</span>, </span>
<span id="cb3-41"><a href="#cb3-41" aria-hidden="true" tabindex="-1"></a>                 <span class="st">&quot;Refused&quot;</span>),</span>
<span id="cb3-42"><a href="#cb3-42" aria-hidden="true" tabindex="-1"></a>      <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Not too familiar&quot;</span>, <span class="st">&quot;Very familiar&quot;</span>, <span class="st">&quot;Refused&quot;</span>)</span>
<span id="cb3-43"><a href="#cb3-43" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb3-44"><a href="#cb3-44" aria-hidden="true" tabindex="-1"></a>    <span class="at">CENIDENTITYc =</span> <span class="fu">factor</span>(</span>
<span id="cb3-45"><a href="#cb3-45" aria-hidden="true" tabindex="-1"></a>      CENIDENTITYc, </span>
<span id="cb3-46"><a href="#cb3-46" aria-hidden="true" tabindex="-1"></a>      <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">&quot;I do not feel a strong connection with the cultural origin of my family&quot;</span>, </span>
<span id="cb3-47"><a href="#cb3-47" aria-hidden="true" tabindex="-1"></a>                 <span class="st">&quot;I feel a strong connection with the cultural origin of my family&quot;</span>, </span>
<span id="cb3-48"><a href="#cb3-48" aria-hidden="true" tabindex="-1"></a>                 <span class="st">&quot;Refused&quot;</span>),</span>
<span id="cb3-49"><a href="#cb3-49" aria-hidden="true" tabindex="-1"></a>      <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Not a strong connection&quot;</span>, <span class="st">&quot;Strong connection&quot;</span>, <span class="st">&quot;Refused&quot;</span>)</span>
<span id="cb3-50"><a href="#cb3-50" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb3-51"><a href="#cb3-51" aria-hidden="true" tabindex="-1"></a>    <span class="at">IDEO =</span> <span class="fu">factor</span>(</span>
<span id="cb3-52"><a href="#cb3-52" aria-hidden="true" tabindex="-1"></a>      IDEO, </span>
<span id="cb3-53"><a href="#cb3-53" aria-hidden="true" tabindex="-1"></a>      <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">&quot;Very conservative&quot;</span>, <span class="st">&quot;Conservative&quot;</span>, <span class="st">&quot;Moderate&quot;</span>, <span class="st">&quot;Liberal&quot;</span>, <span class="st">&quot;Very liberal&quot;</span>, <span class="st">&quot;Refused&quot;</span>),</span>
<span id="cb3-54"><a href="#cb3-54" aria-hidden="true" tabindex="-1"></a>      <span class="at">ordered =</span> <span class="cn">TRUE</span></span>
<span id="cb3-55"><a href="#cb3-55" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb3-56"><a href="#cb3-56" aria-hidden="true" tabindex="-1"></a>    <span class="at">ppagecat =</span> <span class="fu">factor</span>(ppagecat, <span class="at">ordered =</span> <span class="cn">TRUE</span>),</span>
<span id="cb3-57"><a href="#cb3-57" aria-hidden="true" tabindex="-1"></a>    <span class="at">ppagecat =</span> <span class="fu">fct_drop</span>(ppagecat),</span>
<span id="cb3-58"><a href="#cb3-58" aria-hidden="true" tabindex="-1"></a>    <span class="at">ppagect4 =</span> <span class="fu">factor</span>(ppagect4, <span class="at">ordered =</span> <span class="cn">TRUE</span>),</span>
<span id="cb3-59"><a href="#cb3-59" aria-hidden="true" tabindex="-1"></a>    <span class="at">ppagect4 =</span> <span class="fu">fct_drop</span>(ppagect4),</span>
<span id="cb3-60"><a href="#cb3-60" aria-hidden="true" tabindex="-1"></a>    <span class="at">ppeducat =</span> <span class="fu">factor</span>(ppeducat, <span class="at">ordered =</span> <span class="cn">TRUE</span>),</span>
<span id="cb3-61"><a href="#cb3-61" aria-hidden="true" tabindex="-1"></a>    <span class="at">CASEID =</span> <span class="fu">as.character</span>(CASEID),</span>
<span id="cb3-62"><a href="#cb3-62" aria-hidden="true" tabindex="-1"></a>    <span class="at">RACEOE_1 =</span> <span class="fu">factor</span>(<span class="fu">if_else</span>(<span class="sc">!</span><span class="fu">str_detect</span>(RACEOE_1, <span class="st">&quot;^Protest&quot;</span>), <span class="st">&quot;Other&quot;</span>, <span class="st">&quot;Protest&quot;</span>))</span>
<span id="cb3-63"><a href="#cb3-63" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb3-64"><a href="#cb3-64" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb3-65"><a href="#cb3-65" aria-hidden="true" tabindex="-1"></a>    CASEID, weight, simple_eth, CENIDENTITYa, CENIDENTITYb, CENIDENTITYc, IDEO,</span>
<span id="cb3-66"><a href="#cb3-66" aria-hidden="true" tabindex="-1"></a>    RACEOE_1,</span>
<span id="cb3-67"><a href="#cb3-67" aria-hidden="true" tabindex="-1"></a>    ppage, ppagecat, ppagect4, ppeducat, ppgender, ppreg4, </span>
<span id="cb3-68"><a href="#cb3-68" aria-hidden="true" tabindex="-1"></a>    ppreg9, ppstaten</span>
<span id="cb3-69"><a href="#cb3-69" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb3-70"><a href="#cb3-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-71"><a href="#cb3-71" aria-hidden="true" tabindex="-1"></a>pew_dat_1 <span class="sc">%&gt;%</span> skimr<span class="sc">::</span><span class="fu">skim</span>()</span></code></pre></div>
<table>
<caption>Data summary</caption>
<tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">Piped data</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">3535</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">16</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">character</td>
<td align="left">1</td>
</tr>
<tr class="odd">
<td align="left">factor</td>
<td align="left">13</td>
</tr>
<tr class="even">
<td align="left">numeric</td>
<td align="left">2</td>
</tr>
<tr class="odd">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">Group variables</td>
<td align="left">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">min</th>
<th align="right">max</th>
<th align="right">empty</th>
<th align="right">n_unique</th>
<th align="right">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">CASEID</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">4</td>
<td align="right">0</td>
<td align="right">3535</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: factor</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="left">ordered</th>
<th align="right">n_unique</th>
<th align="left">top_counts</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">simple_eth</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="left">FALSE</td>
<td align="right">4</td>
<td align="left">Whi: 2063, His: 750, Oth: 452, Bla: 270</td>
</tr>
<tr class="even">
<td align="left">CENIDENTITYa</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="left">FALSE</td>
<td align="right">3</td>
<td align="left">Not: 2204, Cen: 1199, Ref: 132</td>
</tr>
<tr class="odd">
<td align="left">CENIDENTITYb</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="left">FALSE</td>
<td align="right">3</td>
<td align="left">Ver: 2246, Not: 1188, Ref: 101</td>
</tr>
<tr class="even">
<td align="left">CENIDENTITYc</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="left">FALSE</td>
<td align="right">3</td>
<td align="left">Not: 1726, Str: 1714, Ref: 95</td>
</tr>
<tr class="odd">
<td align="left">IDEO</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="left">TRUE</td>
<td align="right">6</td>
<td align="left">Mod: 1512, Con: 866, Lib: 563, Ver: 319</td>
</tr>
<tr class="even">
<td align="left">RACEOE_1</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="left">FALSE</td>
<td align="right">2</td>
<td align="left">Oth: 3484, Pro: 51</td>
</tr>
<tr class="odd">
<td align="left">ppagecat</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="left">TRUE</td>
<td align="right">7</td>
<td align="left">55-: 779, 35-: 605, 65-: 596, 45-: 553</td>
</tr>
<tr class="even">
<td align="left">ppagect4</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="left">TRUE</td>
<td align="right">4</td>
<td align="left">60+: 1242, 45-: 955, 30-: 847, 18-: 491</td>
</tr>
<tr class="odd">
<td align="left">ppeducat</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="left">TRUE</td>
<td align="right">4</td>
<td align="left">Bac: 1248, Hig: 1004, Som: 966, Les: 317</td>
</tr>
<tr class="even">
<td align="left">ppgender</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="left">FALSE</td>
<td align="right">2</td>
<td align="left">Fem: 1781, Mal: 1754</td>
</tr>
<tr class="odd">
<td align="left">ppreg4</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="left">FALSE</td>
<td align="right">4</td>
<td align="left">Sou: 1301, Wes: 924, Mid: 693, Nor: 617</td>
</tr>
<tr class="even">
<td align="left">ppreg9</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="left">FALSE</td>
<td align="right">9</td>
<td align="left">Sou: 697, Pac: 671, Eas: 503, Mid: 464</td>
</tr>
<tr class="odd">
<td align="left">ppstaten</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="left">FALSE</td>
<td align="right">51</td>
<td align="left">CA: 503, TX: 320, FL: 253, NY: 190</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p25</th>
<th align="right">p50</th>
<th align="right">p75</th>
<th align="right">p100</th>
<th align="left">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">weight</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">1.00</td>
<td align="right">0.68</td>
<td align="right">0.24</td>
<td align="right">0.59</td>
<td align="right">0.82</td>
<td align="right">1.15</td>
<td align="right">4.42</td>
<td align="left">▇▂▁▁▁</td>
</tr>
<tr class="even">
<td align="left">ppage</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">50.99</td>
<td align="right">16.87</td>
<td align="right">18.00</td>
<td align="right">37.00</td>
<td align="right">53.00</td>
<td align="right">64.00</td>
<td align="right">94.00</td>
<td align="left">▅▆▇▆▁</td>
</tr>
</tbody>
</table>
<p>The target population consisted of … The survey sample results were weighted by gender (<code>ppgender</code>), age (<code>ppage</code>, <code>ppagecat</code>, <code>ppagecat4</code>), education (<code>ppeducat</code>), census region (<code>ppreg4</code>, <code>ppreg9</code>, <code>ppstateen</code>), race/ethnicity (<code>CENRACE2020_1</code> and <code>CENHISPAN2020_1</code> which I combined into <code>simple_eth</code>. An open text question asked to self-describe race, <code>RACEOE</code> and I counted instances coded as “protest” in <code>RACEOE_1</code>), internet access, political ideology (<code>IDEO</code>), volunteerism (volunteered, did not volunteer), voter registration (Yes , No), and Country of birth. <code>CASEID</code> is a unique identifier for the weighted group, and <code>weight</code> is the response weight.</p>
<p>Among other questions, the survey asked three yes/no questions (<code>CENIDENTITYa</code>, <code>CENIDENTITYb</code>, and <code>CENIDENTITYc</code>) related to how central the respondent’s cultural origin is to their self-identity.</p>
</div>
<div id="data-exploration" class="section level1">
<h1>Data Exploration</h1>
<div id="importance-of-cultural-origins" class="section level2 tabset">
<h2 class="tabset">Importance of Cultural Origins</h2>
<p>The following figures loosely follow Pew’s 5/14/2021 report, <a href="https://www.pewresearch.org/social-trends/2021/05/14/black-and-hispanic-americans-see-their-origins-as-central-to-who-they-are-less-so-for-white-adults/">Black and Hispanic Americans See Their Origins as Central to Who They Are, Less So for White Adults</a>.</p>
<p>The main conclusion from Pew’s report is that the importance of ancestral roots varies by race and ethnicity. The first, second, and fourth figures in the report are based on three questions about the respondent’s relationship to the cultural origin of their family. Question <code>CENIDENTITYa</code> asked how <em>central</em> their origins are to their identity; Question <code>CENIDENTITYb</code> asked how <em>familiar</em> they are with their origins; and <code>CENIDENTITYc</code> asked how <em>connected</em> the respondent is with their origins.</p>
<!-- :::: logic below creates style html within document -->
<div id="centrality" class="section level3">
<h3>Centrality</h3>
<div style="display: grid; grid-template-columns: 1fr 1fr; grid-column-gap: 10px;">
<div>
<blockquote>
<p>Here is a pair of statements about how you think about your origin (for example, German, Mexican, Jamaican, Chinese, etc.) Which statement comes closer to your view – even if neither is exactly right?</p>
<p>1 My origin is central to my identity</p>
<p>2 My origin is not central to my identity</p>
</blockquote>
</div>
<div>
<p><img src="1_get_data_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
</div>
</div>
</div>
<div id="familiarity" class="section level3">
<h3>Familiarity</h3>
<div style="display: grid; grid-template-columns: 1fr 1fr; grid-column-gap: 10px;">
<div>
<blockquote>
<p>Here is a pair of statements about how you think about your origin (for example, German, Mexican, Jamaican, Chinese, etc.) Which statement comes closer to your view – even if neither is exactly right?</p>
<p>1 I am very familiar with my origins</p>
<p>2 I am not too familiar with my origins</p>
</blockquote>
</div>
<div>
<p><img src="1_get_data_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
</div>
</div>
</div>
<div id="connectedness" class="section level3">
<h3>Connectedness</h3>
<div style="display: grid; grid-template-columns: 1fr 1fr; grid-column-gap: 10px;">
<div>
<blockquote>
<p>Here is a pair of statements about how you think about your origin (for example, German, Mexican, Jamaican, Chinese, etc.) Which statement comes closer to your view – even if neither is exactly right?</p>
<p>1 I feel a strong connection with the cultural origin of my family</p>
<p>2 I do not feel a strong connection with the cultural origin of my family</p>
</blockquote>
</div>
<div>
<p><img src="1_get_data_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
</div>
</div>
</div>
</div>
<div id="relationship-with-social-and-demographic-factors" class="section level2">
<h2>Relationship with Social and Demographic Factors</h2>
<p>The Ipsos survey data includes four social and demographic variables that can further segment the race/ethnicity differences: education, age, gender, and geograph location.</p>
<div id="education" class="section level3 tabset">
<h3 class="tabset">Education</h3>
<p>Variable <code>ppeducat</code> is defined as the highest level of education received. The results below are likely influenced by age since younger respondents are unlikely to have a Bachelor’s degree or higher.</p>
<div id="centrality-1" class="section level4">
<h4>Centrality</h4>
<div style="display: grid; grid-template-columns: 1fr 3fr; grid-column-gap: 10px;">
<div>
<p>There is an inverse relationship between level of education received and the importance of family origins for all three race/ethnicity groups. Black Americans with less than a high school degree are a possible exception.</p>
</div>
<div>
<p><img src="1_get_data_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
</div>
</div>
</div>
<div id="familiarity-1" class="section level4">
<h4>Familiarity</h4>
<div style="display: grid; grid-template-columns: 1fr 3fr; grid-column-gap: 10px;">
<div>
<p>Familiarity with family origins increases with education level for all three race/ethnicity groups. Black Americans with less than a high school degree are a possible exception.</p>
</div>
<div>
<p><img src="1_get_data_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
</div>
</div>
</div>
<div id="connectedness-1" class="section level4">
<h4>Connectedness</h4>
<div style="display: grid; grid-template-columns: 1fr 3fr; grid-column-gap: 10px;">
<div>
<p>A third of white Americans report a strong connection to family origins, a proportion that is not moderated by level of education. There is a mild positive association in connectedness for Black Americans, and a mild negative association with Hispanic Americans.</p>
</div>
<div>
<p><img src="1_get_data_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
</div>
</div>
</div>
</div>
<div id="age" class="section level3 tabset">
<h3 class="tabset">Age</h3>
<p>Variables <code>ppage</code>, <code>ppagecat</code> (7 levels), <code>ppagect4</code> (4 levels) are the respondent’s age.</p>
<div id="centrality-2" class="section level4">
<h4>Centrality</h4>
<div style="display: grid; grid-template-columns: 1fr 3fr; grid-column-gap: 10px;">
<div>
<p>Cultural origins are not central to the identity of White Americans regardless of age (perhaps a mild positive relationship?). For Black Americans there is a bell shaped distribution. For Hispanic Americans, cultural origins are central to identity regardless of age (perhaps a mild negative relationship?).</p>
</div>
<div>
<p><img src="1_get_data_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
</div>
</div>
</div>
<div id="familiarity-2" class="section level4">
<h4>Familiarity</h4>
<div style="display: grid; grid-template-columns: 1fr 3fr; grid-column-gap: 10px;">
<div>
<p>Familiarity with family origins increases with age level for all three race/ethnicity groups. Black Americans over 75 years of age are a possible exception.</p>
</div>
<div>
<p><img src="1_get_data_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
</div>
</div>
</div>
<div id="connectedness-2" class="section level4">
<h4>Connectedness</h4>
<div style="display: grid; grid-template-columns: 1fr 3fr; grid-column-gap: 10px;">
<div>
<p>Connection to family origins does not appear to be related to age for any race/ethnicity.</p>
</div>
<div>
<p><img src="1_get_data_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
</div>
</div>
</div>
</div>
<div id="gender" class="section level3 tabset">
<h3 class="tabset">Gender</h3>
<p>Variable <code>ppgender</code> is the respondent’s gender.</p>
<div id="centrality-3" class="section level4">
<h4>Centrality</h4>
<div style="display: grid; grid-template-columns: 1fr 3fr; grid-column-gap: 10px;">
<div>
<p>White women were slightly more likely than White men to report family cultural origins were central to their identity. For Black Americans the relationship is reversed. Hispanic Women were more much more likely to report a central role for cultural origins than men.</p>
</div>
<div>
<p><img src="1_get_data_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
</div>
</div>
</div>
<div id="familiarity-3" class="section level4">
<h4>Familiarity</h4>
<div style="display: grid; grid-template-columns: 1fr 3fr; grid-column-gap: 10px;">
<div>
<p>Familiarity with family origins is about equal between genders of all three groups.</p>
</div>
<div>
<p><img src="1_get_data_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
</div>
</div>
</div>
<div id="connectedness-3" class="section level4">
<h4>Connectedness</h4>
<div style="display: grid; grid-template-columns: 1fr 3fr; grid-column-gap: 10px;">
<div>
<p>Connection to family origins does not appear to be related to gender for any race/ethnicity.</p>
</div>
<div>
<p><img src="1_get_data_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
</div>
</div>
</div>
</div>
<div id="geography" class="section level3 tabset">
<h3 class="tabset">Geography</h3>
<p>Variables <code>ppstaten</code>, <code>ppreg9</code>, and <code>ppreg4</code> are geographic indicators of the respondent’s residence.</p>
<div id="centrality-4" class="section level4">
<h4>Centrality</h4>
<p>Americans on the coasts were more likely to report family cultural origins were central to their identity.</p>
<p><img src="1_get_data_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
</div>
<div id="familiarity-4" class="section level4">
<h4>Familiarity</h4>
<div style="display: grid; grid-template-columns: 1fr 3fr; grid-column-gap: 10px;">
<div>
<p>Familiarity with family origins is more common in the interior rather than the coasts.</p>
</div>
<div>
<p><img src="1_get_data_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
</div>
</div>
</div>
<div id="connectedness-4" class="section level4">
<h4>Connectedness</h4>
<div style="display: grid; grid-template-columns: 1fr 3fr; grid-column-gap: 10px;">
<div>
<p>Connection to family origins is highest in the Mountain states for Black Americans, and the Atlantic states for Hispanic Americans.</p>
</div>
<div>
<p><img src="1_get_data_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
</div>
</div>
</div>
</div>
</div>
</div>
<div id="save-data" class="section level1">
<h1>Save Data</h1>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">saveRDS</span>(pew_dat_1, <span class="st">&quot;../data/1_get_data.rds&quot;</span>)</span></code></pre></div>
</div>
<div class="footnotes">
<hr />
<ol>
<li id="fn1"><p>Navigate to this survey from the <a href="https://www.pewresearch.org/">Pew Research Center home page</a> by clicking TOOLS &amp; RESOURCES &gt; Dataset Downloads &gt; Social &amp; Demographic Trends &gt; 2020 Census survey #1. You may have to register for a free account.<a href="#fnref1" class="footnote-back">↩︎</a></p></li>
<li id="fn2"><p>The <a href="https://github.com/mpfoley73/pew-2020-census/blob/main/data/Jan20%20Census_methodology.pdf">Jan20 Census_methodology.pdf</a> file located in the project data directory on <a href="https://github.com/mpfoley73/pew-2020-census/tree/main/data">GitHub</a> includes a codebook of census variables.<a href="#fnref2" class="footnote-back">↩︎</a></p></li>
</ol>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
